# Need update
wordpress_download_url: "https://wordpress.org/latest.zip"

# Accelerate download from OSS
wordpress_theme_download_url: "https://libs-websoft9-com.oss-accelerate.aliyuncs.com/apps/wordpress"

# wp-cli refer to: https://make.wordpress.org/cli/
wordpress_cli_url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"


#Web服务器：apache | nginx，通过交互式选择获取
wordpress_webs: apache

wordpress_addapps: ""
wordpress_theme: ""

#数据库连接信息
wordpress_db_password: "123456"

wordpress_vhost_dir: /etc/httpd/conf.d
wordpress_vhost_src: vhost.conf
wordpress_service: httpd
wordpress_owner: apache
wordpress_name: "wordpress"
wordpress_title: "WordPress"