---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    discuz_vhost_dir: "{{php_runtime_meta[ansible_os_family][discuz_webs].vhost_dir}}"
    discuz_vhost_src: "{{php_runtime_meta[ansible_os_family][discuz_webs].vhost_src}}"
    discuz_service: "{{php_runtime_meta[ansible_os_family][discuz_webs].service}}"
    discuz_owner: "{{php_runtime_meta[ansible_os_family][discuz_webs].owner}}"
    discuz_db_password: "{{mysql_root_password}}"

- debug:
    msg: runtime {{ discuz_vhost_dir }}, {{discuz_vhost_src}}, {{discuz_service}}, {{discuz_owner}}, {{discuz_webs}}, {{ansible_distribution}}

# Discuz!X3.4
- name: Remove extra dir
  shell: |
    rm -rf /data/wwwroot/*{{discuz_name}}*

- name: Create discuz directory
  file:
    path: /data/wwwroot/{{discuz_name}}
    state: directory

- name: Download Discuz!X3.4
  git:
    repo: "{{discuz_download_url}}"
    dest: /data/wwwroot/discuz
    version: "{{ discuz_version }}"

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{discuz_name}}" ]; then mv *{{discuz_name}}* {{discuz_name}}; fi

- name: copy discuz config
  template: src=config_global_default.php dest=/data/wwwroot/discuz/upload/config/config_global_default.php

# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{discuz_owner}}:{{discuz_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{discuz_vhost_src}} dest={{discuz_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{discuz_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted

- name: Check wordpress discuz version
  shell: |
    sudo echo "{{wordpress_addapps}} version:" `grep "define('DISCUZ_VERSION'," /data/wwwroot/{{wordpress_addapps}}/upload/source/discuz_version.php | awk -F ',' '{print $2}' | awk -F \' '{print $2}'` |sudo tee -a /data/logs/install_version.txt
  when: addapps_selection != '1'