#商业主题的下载包包含官方源码和主题
#注意：当无插件下载的时，请写：plugin: "" or plugin: False
wordpress_theme_meta:

  avada: 
    theme: "avada"
    version: "v7.3.1"
    plugin:
      - fusion-core
      - fusion-builder
      - LayerSlider
      - revslider
      
  porto: 
    theme: "porto"
    version: "v5.4.6"
    plugin:
      - Ultimate_VC_Addons
      - dynamic-featured-image
      - js_composer
      - porto-functionality
      - revslider
      - sliderrevolution
      - wpbakerybuilder

  the7: 
    theme: "dt-the7"
    version: "v9.13.1.0"
    plugin:
      - Ultimate_VC_Addons
      - dt-the7-core
      - go_pricing
      - js_composer
      - revslider
    
  divi: 
    theme: "Divi"
    version: "v4.5.5"
    plugin: 
      - Divi-Builder-Layouts-147

#组合apps名称
wordpress_addapps_meta:
   discuz:
     title: "Discuz"
     documentroot: "upload"
